# Generated by Django 4.2.3 on 2023-08-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0002_admproducts"),
    ]

    operations = [
        migrations.AddField(
            model_name="admproducts",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="offer_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/admimg/product"
            ),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
    ]
