# Generated by Django 4.2.3 on 2023-08-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0006_alter_admproducts_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admproducts",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
