# Generated by Django 4.2.3 on 2023-08-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0007_alter_admproducts_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="admproducts",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
