# Generated by Django 4.2.3 on 2023-08-05 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0009_rename_category_admproducts_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admproducts",
            old_name="category_id",
            new_name="category",
        ),
    ]
