# Generated by Django 4.2.3 on 2023-08-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0010_rename_category_id_admproducts_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=50)),
                (
                    "color_image",
                    models.ImageField(blank=True, null=True, upload_to="color_images/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adm.admproducts",
                    ),
                ),
            ],
        ),
    ]
