# Generated by Django 4.2.3 on 2023-08-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0011_productcolor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admproducts",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="productcolor",
            name="stock",
        ),
        migrations.AddField(
            model_name="productcolor",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
