# Generated by Django 4.2.3 on 2023-08-07 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0012_remove_admproducts_stock_remove_productcolor_stock_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admproducts",
            old_name="quantity",
            new_name="stock",
        ),
        migrations.RenameField(
            model_name="productcolor",
            old_name="quantity",
            new_name="stock",
        ),
    ]
