# Generated by Django 4.2.3 on 2023-08-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0019_productvariant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="offer_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
