# Generated by Django 4.2.3 on 2023-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0024_remove_admproducts_images_delete_productimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolor",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
