# Generated by Django 4.2.3 on 2023-08-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0028_productcolor_is_active_productsize_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="admproducts",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="variantimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
