# Generated by Django 4.2.3 on 2023-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0029_admproducts_is_active_productvariant_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
    ]
