# Generated by Django 4.2.3 on 2023-09-22 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adm", "0035_remove_coupon_discount_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="active",
        ),
        migrations.AddField(
            model_name="coupon",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserCoupons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adm.coupon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
