# Generated by Django 4.2.3 on 2023-09-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0039_delete_usercoupons"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
