# Generated by Django 4.2.3 on 2023-10-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0043_alter_admproducts_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admproducts",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="adm.admcategories",
            ),
        ),
    ]
