# Generated by Django 4.2.3 on 2023-10-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0047_alter_admcategories_offer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admcategories",
            name="offer_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
