# Generated by Django 4.2.3 on 2023-08-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0022_alter_productvariant_product"),
        ("home", "0013_alter_cartitem_product_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adm.admproducts"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adm.admproducts"
            ),
        ),
    ]
