# Generated by Django 4.2.3 on 2023-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_remove_order_total_price_each"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
