# Generated by Django 4.2.2 on 2023-09-09 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_order_total_price_tax_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price_shipping',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 20, 43, 44, 457288)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 20, 43, 44, 458355)),
        ),
    ]
