# Generated by Django 4.2.3 on 2023-09-13 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_remove_order_total_price_shipping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 13, 12, 33, 44, 106989)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 13, 12, 33, 44, 106989)
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Order Placed", "Order Placed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Return Requested"),
                ],
                default="Order Placed",
                max_length=20,
            ),
        ),
    ]
