# Generated by Django 4.2.3 on 2023-09-24 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0052_cart_coupon_alter_cart_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 24, 18, 15, 36, 541842)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 24, 18, 15, 36, 541842)
            ),
        ),
    ]
