# Generated by Django 4.2.3 on 2023-09-30 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0067_rename_total_price_tax_order_after_tax_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="after_tax_amount",
            new_name="total_price_tax",
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 30, 19, 23, 3, 40321)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 30, 19, 23, 3, 40321)
            ),
        ),
    ]
