# Generated by Django 4.2.3 on 2023-10-01 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0068_rename_after_tax_amount_order_total_price_tax_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 1, 16, 12, 40, 562715)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 1, 16, 12, 40, 562715)
            ),
        ),
    ]
