# Generated by Django 5.1.5 on 2025-01-19 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_alter_cart_created_at_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 19, 15, 16, 52, 175089)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 19, 15, 16, 52, 175636)),
        ),
    ]
