# Generated by Django 4.2.3 on 2023-07-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verify',
            new_name='is_verified',
        ),
    ]
