# Generated by Django 4.2.3 on 2023-08-01 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0003_admproducts_brand_admproducts_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdmCatogories",
            new_name="AdmCategories",
        ),
    ]
