# Generated by Django 4.2.3 on 2023-08-05 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0008_admproducts_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admproducts",
            old_name="category",
            new_name="category_id",
        ),
    ]
