# Generated by Django 4.2.3 on 2023-08-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0014_productsize_rename_color_image_productcolor_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admproducts",
            name="color",
        ),
        migrations.RemoveField(
            model_name="admproducts",
            name="size",
        ),
        migrations.RemoveField(
            model_name="productcolor",
            name="image",
        ),
        migrations.AddField(
            model_name="admproducts",
            name="colors",
            field=models.ManyToManyField(to="adm.productcolor"),
        ),
        migrations.AddField(
            model_name="admproducts",
            name="sizes",
            field=models.ManyToManyField(to="adm.productsize"),
        ),
        migrations.AlterField(
            model_name="productcolor",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
