# Generated by Django 4.2.3 on 2023-08-08 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0015_remove_admproducts_color_remove_admproducts_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admproducts",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="color",
        ),
        migrations.DeleteModel(
            name="ProductColor",
        ),
    ]
