# Generated by Django 4.2.3 on 2023-08-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0016_remove_admproducts_colors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="admproducts",
            name="colors",
            field=models.ManyToManyField(to="adm.productcolor"),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="color",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="adm.productcolor",
            ),
            preserve_default=False,
        ),
    ]
