# Generated by Django 4.2.3 on 2023-08-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0017_productcolor_admproducts_colors_productvariant_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admproducts",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="admproducts",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="admproducts",
            name="offer_price",
        ),
        migrations.RemoveField(
            model_name="admproducts",
            name="price",
        ),
        migrations.RemoveField(
            model_name="admproducts",
            name="sizes",
        ),
        migrations.RemoveField(
            model_name="admproducts",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="offer_price",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="status",
        ),
        migrations.AddField(
            model_name="admproducts",
            name="description",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
