# Generated by Django 4.2.3 on 2023-08-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0023_productimage_variantimage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admproducts",
            name="images",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.AddField(
            model_name="admproducts",
            name="images",
            field=models.ImageField(default=0, upload_to="product_images/"),
            preserve_default=False,
        ),
    ]
