# Generated by Django 4.2.3 on 2023-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0026_admproducts_offer_price_admproducts_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="admcategories",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
