# Generated by Django 4.2.3 on 2023-09-20 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0030_productvariant_popularity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="popularity",
        ),
    ]
