# Generated by Django 4.2.3 on 2023-09-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0033_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="coupon_code",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[("amount", "Amount"), ("percentage", "Percentage")],
                max_length=50,
            ),
        ),
    ]
