# Generated by Django 4.2.3 on 2023-09-22 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0034_alter_coupon_coupon_code_alter_coupon_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="discount_type",
        ),
    ]
