# Generated by Django 4.2.3 on 2023-09-22 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0037_alter_coupon_is_expired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="offer_name",
        ),
    ]
