# Generated by Django 4.2.3 on 2023-09-24 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0038_remove_productvariant_discount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCoupons",
        ),
    ]
