# Generated by Django 4.2.3 on 2023-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0040_productvariant_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="admproducts",
            name="offer_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
