# Generated by Django 4.2.3 on 2023-09-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0042_admproducts_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admproducts",
            name="discount_percentage",
            field=models.IntegerField(),
        ),
    ]
