# Generated by Django 4.2.3 on 2023-10-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0044_alter_admproducts_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admproducts",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="adm.admcategories",
            ),
            preserve_default=False,
        ),
    ]
