# Generated by Django 4.2.3 on 2023-10-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adm", "0045_alter_admproducts_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="admcategories",
            name="offer_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
