# Generated by Django 4.2.3 on 2023-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_address_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="house_name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="postoffice",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
