# Generated by Django 4.2.3 on 2023-08-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_address_address_address_house_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(default="", max_length=100),
        ),
    ]
