# Generated by Django 4.2.3 on 2023-08-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_address_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=100),
        ),
    ]
