# Generated by Django 4.2.3 on 2023-08-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_delete_productcolor_delete_productsize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="house_name",
        ),
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(
                default=0, max_length=100, verbose_name="House or Company Name"
            ),
            preserve_default=False,
        ),
    ]
