# Generated by Django 4.2.3 on 2023-08-18 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_order_total_price_each"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price_each",
        ),
    ]
