# Generated by Django 4.2.3 on 2023-08-18 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_order_total_price_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price_quantity",
        ),
    ]
