# Generated by Django 4.2.2 on 2023-08-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_order_total_price_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Order Placed', 'ORDER PLACED'), ('Shipped', 'SHIPPED'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='Order Placed', max_length=20),
        ),
    ]
