# Generated by Django 4.2.3 on 2023-09-08 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_alter_cartitem_product_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 8, 19, 12, 3, 69372)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 8, 19, 12, 3, 69372)
            ),
        ),
    ]
