# Generated by Django 4.2.2 on 2023-09-09 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_cart_created_at_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 20, 36, 41, 509914)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 20, 36, 41, 509914)),
        ),
    ]
