# Generated by Django 4.2.3 on 2023-09-20 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_alter_cart_created_at_alter_order_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="refund_added_to_wallet",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 20, 13, 36, 18, 802789)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 20, 13, 36, 18, 802789)
            ),
        ),
    ]
