# Generated by Django 4.2.3 on 2023-09-29 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0066_remove_cart_cart_total_alter_cart_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_price_tax",
            new_name="after_tax_amount",
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 29, 16, 6, 15, 256473)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 29, 16, 6, 15, 256473)
            ),
        ),
    ]
